<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="tubas-MBP.lan" name="com.qa.verizon.test.PhoneTest" tests="7" failures="1" timestamp="1 Aug 2020 03:04:56 GMT" time="15.120" errors="0">
  <testcase name="ChooseColorAndPrice" time="1.143" classname="com.qa.verizon.test.PhoneTest"/>
  <testcase name="Chooseplan" time="5.266" classname="com.qa.verizon.test.PhoneTest"/>
  <testcase name="VerifyTitle" time="0.096" classname="com.qa.verizon.test.PhoneTest">
    <failure type="java.lang.AssertionError" message="expected [New Apple iPhone 11 - 6 Cool Colors &amp; Dual Camera | Best Price] but found [Apple iPhone 11 - 6 Cool Colors &amp; Dual Camera | Best Price]">
      <![CDATA[java.lang.AssertionError: expected [New Apple iPhone 11 - 6 Cool Colors & Dual Camera | Best Price] but found [Apple iPhone 11 - 6 Cool Colors & Dual Camera | Best Price]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.qa.verizon.test.PhoneTest.VerifyTitle(PhoneTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- VerifyTitle -->
  <testcase name="SelectNextButton" time="3.516" classname="com.qa.verizon.test.PhoneTest"/>
  <testcase name="SelectDeclineButton" time="0.800" classname="com.qa.verizon.test.PhoneTest"/>
  <testcase name="VerifyPhone" time="4.289" classname="com.qa.verizon.test.PhoneTest"/>
  <testcase name="getSecondTitle" time="0.010" classname="com.qa.verizon.test.PhoneTest"/>
</testsuite> <!-- com.qa.verizon.test.PhoneTest -->
